// <auto-generated>
// 由 BoomFramework.UIPartialGenerator 自动生成，请勿手动修改
// </auto-generated>

using System.Collections;
using System.Collections.Generic;
using TMPro;
using UnityEngine;
using UnityEngine.UI;

namespace BoomFramework
{
    public partial class AboutUI
    {
        public Image pic_img;
        public RectTransform pic_rect;
        public Button 我是按钮_btn;
        public TMP_Text 我是按钮内容_tmptxt;
        public RectTransform 我是按钮内容_rect;
        private void Awake()
        {
            pic_img = transform.FindComponent<Image>("pic@img_rect");
            pic_rect = transform.FindComponent<RectTransform>("pic@img_rect");
            我是按钮_btn = transform.FindComponent<Button>("我是按钮@btn");
            我是按钮内容_tmptxt = transform.FindComponent<TMP_Text>("我是按钮内容@tmptxt_rect");
            我是按钮内容_rect = transform.FindComponent<RectTransform>("我是按钮内容@tmptxt_rect");
        }
    }
}
